### ISSUE TITLE
I don't understand that there is no query input in the README

### ISSUE THREAD

**Issue by dorianmariefr** [ankane/autosuggest#1]
I don't understand, isn't this supposed to be a gem that autocompletes user input? The user input is not passed at all in the example

**Comment by ankane** [comment]
Hey @dorianmariefr, you'll likely want to store the suggestions in your database, and then use a JavaScript library to show them to users based on what's typed.

**Comment by satyakam-nividata** [comment]
Hey @ankane, It'll be great if you can provide one sample for How to use Javascript for this usecase. I provided top_searches and parse words. I got this results 

`{:query=>"business", :original_query=>nil, :score=>261, :duplicate=>nil, :concepts=>[], :misspelling=>false, :profane=>false, :blocked=>false, :notes=>[]}
{:query=>"free download", :original_query=>nil, :score=>216, :duplicate=>nil, :concepts=>[], :misspelling=>false, :profane=>false, :blocked=>false, :notes=>[]}
{:query=>"education", :original_query=>nil, :score=>209, :duplicate=>nil, :concepts=>[], :misspelling=>false, :profane=>false, :blocked=>false, :notes=>[]}
{:query=>"covid", :original_query=>nil, :score=>160, :duplicate=>nil, :concepts=>[], :misspelling=>false, :profane=>false, :blocked=>false, :notes=>[]}`

So How can I use to show suggestions for search term "school" ?

**Comment by dorianmariefr** [comment]
@ankane so the javascript library will have to load all suggestions?

**Comment by ankane** [comment]
Thanks for helping @cspeer!

To all: I've added more details to the readme and the next release will include a simple model generator. Hopefully this will make things more clear. The exact code for showing suggestions will depend on both your JavaScript autocomplete library and how you decide to load data into it (for a few thousand suggestions you can load all of them, and for more, you'll likely want to load a subset when a user begins typing). I recommend checking out the docs for your JavaScript autocomplete library to get a better understanding.
