### ISSUE TITLE
Issue with really long query strings

### ISSUE THREAD

**Issue by indokathan** [ankane/autosuggest#2]
Noticed that when queries are too long, calling `Autosuggest.new(top_queries).suggestions` will hang up 

After deleting (in my case searchjoy searches), everything functions as normal. 

Any ideas?

**Comment by ankane** [comment]
Hey @indokathan, can you share a query string that causes it to hang?

**Comment by indokathan** [comment]
Hi @ankane, the query was: 

_CHUWI Hipad X Android 10.0 Tablet PC, 10.1 inch Unlocked Phablet 4G LTE with Dual Micro SIM, RAM 4G / ROM 128G, Support GPS, OTG, FM, G-Sensor, Light Sensor, TF Card, BT 5.0, Dual WiFi_

You can also replicate the issue with any string around that same length. 

My current fix is to add a LENGTH() check when fetching my searchjoy searches: 

`Searchjoy::Search.group(:normalized_query).having("COUNT(query) >= 3 AND LENGTH(query) <= 60").distinct.count`

Thanks!

**Comment by ankane** [comment]
Thanks @indokathan, was able to reproduce. Found the issue - just need to figure out the best way to solve it.

**Comment by ankane** [comment]
Hey @indokathan, should be fixed if you want to try the version from GitHub.

**Comment by ankane** [comment]
Just pushed a new release with the fix. Thanks again for reporting!
